### ISSUE TITLE
Update protocol buffer performance of Pydantic v2

### ISSUE THREAD

**Issue by jimkring** [iwishiwasaneagle/janhendrikewers.uk#29]
I'd love to see how Pydantic v2 compares to the other options :)

Referring to this blog article: https://janhendrikewers.uk/pydantic_vs_protobuf_vs_namedtuple_vs_dataclasses.html

**Comment by iwishiwasaneagle** [comment]
Hi @jimkring , I compared v1 to v2 in this post here! https://janhendrikewers.uk/pydantic-1-vs-2-a-benchmark-test.html

**Comment by jimkring** [comment]
Great article! Thanks.
